//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIPerson.WcfSvcPerson {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="queryAge_Result", Namespace="http://schemas.datacontract.org/2004/07/DALPersonEF")]
    [System.SerializableAttribute()]
    public partial class queryAge_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FavField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fav {
            get {
                return this.FavField;
            }
            set {
                if ((object.ReferenceEquals(this.FavField, value) != true)) {
                    this.FavField = value;
                    this.RaisePropertyChanged("Fav");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfSvcPerson.ISvsPerson")]
    public interface ISvsPerson {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvsPerson/DoWork", ReplyAction="http://tempuri.org/ISvsPerson/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvsPerson/DoWork", ReplyAction="http://tempuri.org/ISvsPerson/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvsPerson/GetPersonLong", ReplyAction="http://tempuri.org/ISvsPerson/GetPersonLongResponse")]
        UIPerson.WcfSvcPerson.GetPersonLongResponse GetPersonLong(UIPerson.WcfSvcPerson.GetPersonLongRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvsPerson/GetPersonLong", ReplyAction="http://tempuri.org/ISvsPerson/GetPersonLongResponse")]
        System.Threading.Tasks.Task<UIPerson.WcfSvcPerson.GetPersonLongResponse> GetPersonLongAsync(UIPerson.WcfSvcPerson.GetPersonLongRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPersonLong", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPersonLongRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Age;
        
        public GetPersonLongRequest() {
        }
        
        public GetPersonLongRequest(int Age) {
            this.Age = Age;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPersonLongResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPersonLongResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public UIPerson.WcfSvcPerson.queryAge_Result[] GetPersonLongResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string currentTime;
        
        public GetPersonLongResponse() {
        }
        
        public GetPersonLongResponse(UIPerson.WcfSvcPerson.queryAge_Result[] GetPersonLongResult, string currentTime) {
            this.GetPersonLongResult = GetPersonLongResult;
            this.currentTime = currentTime;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISvsPersonChannel : UIPerson.WcfSvcPerson.ISvsPerson, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SvsPersonClient : System.ServiceModel.ClientBase<UIPerson.WcfSvcPerson.ISvsPerson>, UIPerson.WcfSvcPerson.ISvsPerson {
        
        public SvsPersonClient() {
        }
        
        public SvsPersonClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SvsPersonClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvsPersonClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvsPersonClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UIPerson.WcfSvcPerson.GetPersonLongResponse UIPerson.WcfSvcPerson.ISvsPerson.GetPersonLong(UIPerson.WcfSvcPerson.GetPersonLongRequest request) {
            return base.Channel.GetPersonLong(request);
        }
        
        public UIPerson.WcfSvcPerson.queryAge_Result[] GetPersonLong(int Age, out string currentTime) {
            UIPerson.WcfSvcPerson.GetPersonLongRequest inValue = new UIPerson.WcfSvcPerson.GetPersonLongRequest();
            inValue.Age = Age;
            UIPerson.WcfSvcPerson.GetPersonLongResponse retVal = ((UIPerson.WcfSvcPerson.ISvsPerson)(this)).GetPersonLong(inValue);
            currentTime = retVal.currentTime;
            return retVal.GetPersonLongResult;
        }
        
        public System.Threading.Tasks.Task<UIPerson.WcfSvcPerson.GetPersonLongResponse> GetPersonLongAsync(UIPerson.WcfSvcPerson.GetPersonLongRequest request) {
            return base.Channel.GetPersonLongAsync(request);
        }
    }
}
